#!/bin/bash

for i in "$@"
do
case $i in

    # local build for origin/develop to tech staging
    staging)
    export OUTPUT_HOST="http://staging.phenomenon.com"
    export OUTPUT_PORT=80
    export OUTPUT_DIR="html"
    compress=true
    shift
    ;;

    # local build for hosted dev server
    dev)
    export OUTPUT_HOST="http://dev.phenomenon.com"
    export OUTPUT_PORT=80
    export OUTPUT_DIR="public-dev"
    compress=true
    shift
    ;;

    # local build for SimpleHTTPServer
    local)
    export OUTPUT_HOST="http://localhost"
    export OUTPUT_PORT=8000
    export OUTPUT_DIR="public"
    export NODE_ENV="production"
    compress=false
    shift
    ;;

    # local build for origin/master to phenomenon.com
    pub)
    export OUTPUT_HOST="http://phenomenon.com"
    export OUTPUT_PORT=80
    export OUTPUT_DIR="html"
    export NODE_ENV="production"
    compress=true
    shift
    ;;    

esac
shift # past argument or value
done

echo Building directory ./${OUTPUT_DIR} for ${OUTPUT_HOST}:${OUTPUT_PORT}

./node_modules/.bin/webpack --progress

# create tar ball
if [ "$compress" = true ] ; then
    echo Compressing build and nginx configuration files into tar file...
    tar czvf pheno-com.tar.gz nginx "$OUTPUT_DIR"
    echo Cleaning up build artifacts...
    rm -rf $OUTPUT_DIR
fi

# if dev, automatically upload (since this is not handled by jenkins)
if [ "$i" = dev ] ; then
    echo Uploading pheno-com.tar.gz to dev.phenomenon.com...
    scp pheno-com.tar.gz ec2-user@dev.phenomenon.com:pheno-com.tar.gz
    echo Decompressing archive on remote server...
    ssh ec2-user@dev.phenomenon.com "tar zxvf pheno-com.tar.gz"
fi